// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/qimengxingyuan/young_engine/biz/dal"
	"github.com/qimengxingyuan/young_engine/biz/handler"
)

func main() {
	Init()
	r := server.Default()

	// r.GET("/ping", handler.Ping)

	v1 := r.Group("/api/v1")
	v1.POST("/engine/run", handler.HandleRunRule)
	v1.POST("/engine/exp/new", handler.HandleAddExpression)
	v1.GET("/engine/exp/list", handler.HandleGetAllExpression)
	v1.DELETE("/engine/exp/:id", handler.HandleDeleteExpression)
	v1.POST("/engine/exp/run", handler.HandleRunExpression)

	r.Spin()
}

func Init() {
	dal.InitDB()
}
